name: Build and Test

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
          sudo apt-get install lua5.1
          sudo apt-get install luarocks
          sudo apt-get install gcc-arm-none-eabi
          sudo luarocks install luafilesystem
          sudo luarocks install lpack
          sudo luarocks install md5
          

    - name: Build elua
      run: |
        lua .circleci/ci_builder.lua
  build-mac:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
          brew install lua
          brew install luarocks
          brew install gcc-arm-none-eabi
          luarocks install luafilesystem
          luarocks install lpack
          luarocks install md5
          

    - name: Build elua
      run: |
        lua .circleci/ci_builder.lua